data:
  root: data
  cache_ttl_minutes: 120
model:
  seq_len: 120
  target: horizon_return
  horizons: [5, 10, 20]
train:
  batch_size: 256
  epochs: 50
  early_stop_patience: 10
  lr: 5e-4
  optimizer: adamw
feature:
  mi_top_k: 180
  importance_prune_pct: 0.1
serve:
  host: 0.0.0.0
  port: 8080
